/**
 * Root layout — wraps EVERY page (marketing, auth, dashboard).
 *
 * Responsibilities:
 *  1. Load self-hosted Geist fonts and expose them as CSS variables so
 *     Tailwind (and any component) can reference `font-sans` / `font-mono`
 *     without knowing the actual font name.
 *  2. Mount the ThemeProvider once at the root so `next-themes` can write
 *     the `class="dark"` attribute on <html> before paint (preventing the
 *     classic flash-of-wrong-theme).
 *  3. Provide default metadata (open graph, viewport) that child pages
 *     override with their own.
 */

import type { Metadata, Viewport } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { ThemeProvider } from "@/components/shared/theme-provider";
import { assertProductionEnv } from "@/lib/env";
import { cn } from "@/lib/utils";
import "./globals.css";

// Boot-time env invariants — throws fast if a production deploy is missing
// a required secret. No-op in dev. See lib/env.ts.
assertProductionEnv();

// Resolves to NEXT_PUBLIC_APP_URL in production, localhost in dev. Without
// this, OG/Twitter image URLs in social previews fall back to localhost,
// which renders broken cards everywhere except local browsers.
const APP_URL =
  process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";

export const metadata: Metadata = {
  metadataBase: new URL(APP_URL),
  title: {
    default: "Orqestra — AI Workflow Orchestration",
    template: "%s · Orqestra",
  },
  description:
    "Design, run, and ship production-grade AI workflows. Orqestra is the visual orchestration platform for teams building with large language models.",
  keywords: [
    "AI workflow",
    "LLM orchestration",
    "AI automation",
    "Claude",
    "Anthropic",
    "visual workflow builder",
  ],
  authors: [{ name: "Orqestra" }],
  creator: "Orqestra",
  openGraph: {
    type: "website",
    title: "Orqestra — AI Workflow Orchestration",
    description:
      "Design, run, and ship production-grade AI workflows. Visual. Versioned. Fast.",
    siteName: "Orqestra",
  },
  twitter: {
    card: "summary_large_image",
    title: "Orqestra — AI Workflow Orchestration",
    description:
      "Design, run, and ship production-grade AI workflows. Visual. Versioned. Fast.",
  },
  // Favicon + OG + Twitter images are generated by Next file conventions:
  //   src/app/icon.tsx
  //   src/app/opengraph-image.tsx
  //   src/app/twitter-image.tsx
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0b" },
  ],
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(GeistSans.variable, GeistMono.variable)}
    >
      <body
        className={cn(
          "min-h-screen bg-background font-sans text-foreground antialiased",
        )}
        style={
          {
            "--font-sans": GeistSans.style.fontFamily,
            "--font-mono": GeistMono.style.fontFamily,
          } as React.CSSProperties
        }
      >
        {/*
          `disableTransitionOnChange` is intentional — without it, every
          color in the app would tween between themes when the user toggles,
          which looks janky on something this dense. We want an instant swap.
        */}
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
